import { Poppins } from "next/font/google";
import OpenAsideProvider from "@/contexts/OpenAsideProvider";
import "./globals.css";

const poppins = Poppins({ subsets: ["latin"],weight : ["300","400","500","700"]});

export const metadata = {
  title: "Local Mail",
  description: "Generated by Code IT",
};

export default function RootLayout({ children }) {
  return (
    <OpenAsideProvider>
      <html lang="en">
        <body className={poppins.className + " txtNorm lighter-1"}>{children}</body>
      </html>
    </OpenAsideProvider>
  );
}
